export { default as plainTextToDoc } from './plain-text-to-doc'
export { default as plainTextFromEditor } from './plain-text-from-editor'
export { default as plainTextFromRange } from './plain-text-from-range'
export { default as insertPlainText } from './insert-plain-text'
export { default as shouldApplyExternalText } from './should-apply-external-text'
export { default as splitOnShiftEnter } from './split-on-shift-enter'
